/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:018e2932-8fa1-4054-a87b-4b585677c1e9",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ZWj7dqL5V",
    "aws_user_pools_web_client_id": "7dav55n5sg32dv0rc6jubpr3jk",
    "oauth": {}
};


export default awsmobile;
